#!/usr/bin/with-contenv bash

#exec s6-setuidgid root /usr/sbin/slapd -d trace -F /config/openldap-conf/

ulimit -n 1024

exec s6-setuidgid root /usr/sbin/slapd -u abc -g abc -d stats -F /config/openldap/slapd.d -h "ldap:/// ldaps:///"
