#!/usr/bin/with-contenv bash
#
#
set +x

mkdir -p \
  /run/openldap \
  /config \
  /config/openldap-data \
  /config/openldap-conf \
  /config/openldap-conf/ldif 

chown abc:abc -R /config

LDAP_ROOT_PW=""
SLAPD_CONF="/config/openldap-conf/slapd.ldif"

# This is a hack and will overwrite values, when we move to running out of /config
# i think it will all be fixed
cp -a /defaults/slapd.ldif ${SLAPD_CONF}
cp -a /defaults/ldif/org.ldif /config/openldap-conf/ldif/org.ldif

if [ ! -f /config/openldap-conf/ldap_root_pw ]; then
  GENERATED_PW="$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 32| head -n 1)"
  echo ${GENERATED_PW} > /config/openldap-conf/ldap_root_pw
fi

LDAP_ROOT_PW="$(/usr/sbin/slappasswd -s $(cat /config/openldap-conf/ldap_root_pw))"

sed -i "s~%TKF_ROOTPW%~${LDAP_ROOT_PW}~g" ${SLAPD_CONF}
sed -i "s~%TKF_ORG_DN%~${ORG_DN}~g" ${SLAPD_CONF}
sed -i "s~%TKF_ACCESS_CONTROL%~${ACCESS_CONTROL}~g" ${SLAPD_CONF}


if [ ! -d /config/openldap-conf/cn=config ]; then

  #initialize the DB 
  /usr/sbin/slapadd \
    -d trace \
    -n 0 \
    -F /config/openldap-conf \
    -l /config/openldap-conf/slapd.ldif \
    > /config/slapd.log 2>&1

  sed -i "s~%TKF_ORG_DN%~${ORG_DN}~g" /config/openldap-conf/ldif/org.ldif
  sed -i "s~%TKF_ORG_NAME%~${ORG_NAME}~g" /config/openldap-conf/ldif/org.ldif
  # TODO expose domain name as a env var or compute it
  sed -i "s~%LDAP_DOMAIN%~teknofile~g" /config/openldap-conf/ldif/org.ldif

  /usr/bin/ldapadd -x -D "cn=admin,${ORG_DN}" -W -f /config/openldap-conf/ldif/org.ldif
fi
