#!/usr/bin/with-contenv bash
#
#
set +x

CONF_DIR="/config/openldap"
DATA_DIR="/config/data"

mkdir -p \
  /run/openldap \
  /config \
  ${DATA_DIR} \
  ${CONF_DIR} \
  ${CONF_DIR}/ldif 


# Let's see if ${CONF_DIR}/cn=config exists, if itdoes,we'll use it
# if it doesn't let's initialize a new ldap directory
if [ ! -d ${CONF_DIR}/cn=config ]; then
  # The slapd.ldif file is what we use to configure a
  # base ldap database. This is similar to the old way
  # of configuring slapd via the slapd.conf file
  # but these days it's all ldif based and stored in
  # ldap at {0}
  SLAPD_CONF="${CONF_DIR}/slapd.ldif"
  cp -a /defaults/slapd.ldif ${SLAPD_CONF}
  cp -a /defaults/ldif/org.ldif ${CONF_DIR}/ldif/org.ldif

  # We are going to generate a random password
  # And store it on the fs
  if [ ! -f ${CONF_DIR}/ldap_root_pw ]; then
    GENERATED_PW="$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 32| head -n 1)"
    echo ${GENERATED_PW} > ${CONF_DIR}/ldap_root_pw
  fi

  # LDAP_PW is the un-encrypted LDAP admin pw
  # LDAP_ROOT_PW is the encrypted SSHA pw
  LDAP_PW=$(cat ${CONF_DIR}/ldap_root_pw)
  LDAP_ROOT_PW="$(/usr/sbin/slappasswd -s $(cat ${CONF_DIR}/ldap_root_pw))"

  # Now let's go ahead and search/replace the default slapd.ldif
  # file with parameters from the contianers enviornment
  sed -i "s~%TKF_ROOTPW%~${LDAP_ROOT_PW}~g" ${SLAPD_CONF}
  sed -i "s~%TKF_ORG_DN%~${ORG_DN}~g" ${SLAPD_CONF}
  sed -i "s~%TKF_ACCESS_CONTROL%~${ACCESS_CONTROL}~g" ${SLAPD_CONF}
  sed -i "s~%TKF_DB_DIR%~${DATA_DIR}~g" ${SLAPD_CONF}

  #initialize the DB 
  /usr/sbin/slapadd \
    -d trace \
    -n 0 \
    -F ${CONF_DIR} \
    -l ${CONF_DIR}/slapd.ldif \
    > ${CONF_DIR}/slapd.log 2>&1

  # Now we need to setup the base organizationalUnit for the ldap tree
  sed -i "s~%TKF_ORG_DN%~${ORG_DN}~g" ${CONF_DIR}/ldif/org.ldif
  sed -i "s~%TKF_ORG_NAME%~${ORG_NAME}~g" ${CONF_DIR}/ldif/org.ldif
  # TODO expose domain name as a env var or compute it

  LDAP_DOMAIN=`echo ${ORG_DN} | awk -F, '{print $1}' | awk -F= '{print $2}'`
  sed -i "s~%LDAP_DOMAIN%~${LDAP_DOMAIN}~g" ${CONF_DIR}/ldif/org.ldif


  # we have to (temporarily start up the server to do the base add)
  /usr/sbin/slapd -F ${CONF_DIR}

  /usr/bin/ldapadd \
    -f ${CONF_DIR}/ldif/org.ldif \
    -x \
    -D cn=admin,${ORG_DN} \
    -w ${LDAP_PW}

  # Now we kill it off, because we'll start it via s6 later
  kill `pidof slapd`
fi

chown -R abc:abc /config
chown -R abc:abc /run/openldap
